name: react-native-android-build-for-debug-apk
on:
  push:
    branches:
      - develop
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
      - name: Install yarn dependencies
        with:
          cmd: install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
      - name: Install yarn dependencies
        with:
          cmd: install
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-debug-release.apk
          path: android/app/build/outputs/apk/release/
